spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pinger
    username: umaralikhon
    password: 1111

  jpa:
    show-sql: on
    generate-ddl: on
    hibernate:
      ddl-auto: update

props:
  token: '*****'
  base-query-url: 'https://api.telegram.org/bot%s/sendMessage?chat_id=%s&text=%s'
  base-method-url: 'https://api.telegram.org/bot%s/%s'
  bot-name: '@*****'
  chat-id: '-*****'

  source: 'API'